// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/repository.go
//

// Package mock_association is a generated GoMock package.
package mock_association

import (
	context "context"
	reflect "reflect"

	core "github.com/concrnt/concrnt/core"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Clean mocks base method.
func (m *MockRepository) Clean(ctx context.Context, ccid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clean", ctx, ccid)
	ret0, _ := ret[0].(error)
	return ret0
}

// Clean indicates an expected call of Clean.
func (mr *MockRepositoryMockRecorder) Clean(ctx, ccid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clean", reflect.TypeOf((*MockRepository)(nil).Clean), ctx, ccid)
}

// Count mocks base method.
func (m *MockRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRepository)(nil).Count), ctx)
}

// Create mocks base method.
func (m *MockRepository) Create(ctx context.Context, association core.Association) (core.Association, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, association)
	ret0, _ := ret[0].(core.Association)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockRepositoryMockRecorder) Create(ctx, association any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepository)(nil).Create), ctx, association)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, id string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, id)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, id string) (core.Association, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(core.Association)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, id)
}

// GetBySchema mocks base method.
func (m *MockRepository) GetBySchema(ctx context.Context, messageID, schema string) ([]core.Association, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySchema", ctx, messageID, schema)
	ret0, _ := ret[0].([]core.Association)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySchema indicates an expected call of GetBySchema.
func (mr *MockRepositoryMockRecorder) GetBySchema(ctx, messageID, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySchema", reflect.TypeOf((*MockRepository)(nil).GetBySchema), ctx, messageID, schema)
}

// GetBySchemaAndVariant mocks base method.
func (m *MockRepository) GetBySchemaAndVariant(ctx context.Context, messageID, schema, variant string) ([]core.Association, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBySchemaAndVariant", ctx, messageID, schema, variant)
	ret0, _ := ret[0].([]core.Association)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetBySchemaAndVariant indicates an expected call of GetBySchemaAndVariant.
func (mr *MockRepositoryMockRecorder) GetBySchemaAndVariant(ctx, messageID, schema, variant any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBySchemaAndVariant", reflect.TypeOf((*MockRepository)(nil).GetBySchemaAndVariant), ctx, messageID, schema, variant)
}

// GetByTarget mocks base method.
func (m *MockRepository) GetByTarget(ctx context.Context, targetID string) ([]core.Association, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByTarget", ctx, targetID)
	ret0, _ := ret[0].([]core.Association)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByTarget indicates an expected call of GetByTarget.
func (mr *MockRepositoryMockRecorder) GetByTarget(ctx, targetID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByTarget", reflect.TypeOf((*MockRepository)(nil).GetByTarget), ctx, targetID)
}

// GetCountsBySchema mocks base method.
func (m *MockRepository) GetCountsBySchema(ctx context.Context, messageID string) (map[string]int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCountsBySchema", ctx, messageID)
	ret0, _ := ret[0].(map[string]int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCountsBySchema indicates an expected call of GetCountsBySchema.
func (mr *MockRepositoryMockRecorder) GetCountsBySchema(ctx, messageID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCountsBySchema", reflect.TypeOf((*MockRepository)(nil).GetCountsBySchema), ctx, messageID)
}

// GetCountsBySchemaAndVariant mocks base method.
func (m *MockRepository) GetCountsBySchemaAndVariant(ctx context.Context, messageID, schema string) (*core.OrderedKVMap[int64], error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCountsBySchemaAndVariant", ctx, messageID, schema)
	ret0, _ := ret[0].(*core.OrderedKVMap[int64])
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCountsBySchemaAndVariant indicates an expected call of GetCountsBySchemaAndVariant.
func (mr *MockRepositoryMockRecorder) GetCountsBySchemaAndVariant(ctx, messageID, schema any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCountsBySchemaAndVariant", reflect.TypeOf((*MockRepository)(nil).GetCountsBySchemaAndVariant), ctx, messageID, schema)
}

// GetOwn mocks base method.
func (m *MockRepository) GetOwn(ctx context.Context, author string) ([]core.Association, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwn", ctx, author)
	ret0, _ := ret[0].([]core.Association)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwn indicates an expected call of GetOwn.
func (mr *MockRepositoryMockRecorder) GetOwn(ctx, author any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwn", reflect.TypeOf((*MockRepository)(nil).GetOwn), ctx, author)
}

// GetOwnByTarget mocks base method.
func (m *MockRepository) GetOwnByTarget(ctx context.Context, targetID, author string) ([]core.Association, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOwnByTarget", ctx, targetID, author)
	ret0, _ := ret[0].([]core.Association)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOwnByTarget indicates an expected call of GetOwnByTarget.
func (mr *MockRepositoryMockRecorder) GetOwnByTarget(ctx, targetID, author any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOwnByTarget", reflect.TypeOf((*MockRepository)(nil).GetOwnByTarget), ctx, targetID, author)
}
