apiVersion: apps/v1
kind: Deployment
metadata:
  name: concurrent
spec:
  replicas: 1
  selector:
    matchLabels:
      name: concurrent
  template:
    metadata:
      labels:
        name: concurrent
    spec:
      containers:
      - name: concurrent
        image: ghcr.io/totegamma/concurrent:master
        ports:
          - containerPort: 8000
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 3
          periodSeconds: 3
      - name: posgresql
        image: postgres
        ports:
          - containerPort: 5432
        imagePullPolicy: Always
        env:
          - name: POSTGRES_USER
            value: postgres
          - name: POSTGRES_PASSWORD
            value: postgres
          - name: POSTGRES_DB
            value: concurrent
        volumeMounts:
          - name: postgres-varlib
            mountPath: /var/lib/postgresql
      - name: redis
        image: redis
        ports:
          - containerPort: 6379
        imagePullPolicy: Always
        volumeMounts:
          - name: redis-data
            mountPath: /data
      volumes:
        - name: postgres-varlib
          persistentVolumeClaim:
            claimName: postgres-varlib
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-data

