// Code generated by MockGen. DO NOT EDIT.
// Source: client.go
//
// Generated by this command:
//
//	mockgen -source=client.go -destination=mock/client.go
//

// Package mock_client is a generated GoMock package.
package mock_client

import (
	context "context"
	http "net/http"
	reflect "reflect"
	time "time"

	client "github.com/concrnt/concrnt/client"
	core "github.com/concrnt/concrnt/core"
	websocket "github.com/gorilla/websocket"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Commit mocks base method.
func (m *MockClient) Commit(ctx context.Context, domain, body string, response any, opts *client.Options) (*http.Response, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Commit", ctx, domain, body, response, opts)
	ret0, _ := ret[0].(*http.Response)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Commit indicates an expected call of Commit.
func (mr *MockClientMockRecorder) Commit(ctx, domain, body, response, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Commit", reflect.TypeOf((*MockClient)(nil).Commit), ctx, domain, body, response, opts)
}

// ConnectWebsocket mocks base method.
func (m *MockClient) ConnectWebsocket(ctx context.Context, domain, path string) (*websocket.Conn, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ConnectWebsocket", ctx, domain, path)
	ret0, _ := ret[0].(*websocket.Conn)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ConnectWebsocket indicates an expected call of ConnectWebsocket.
func (mr *MockClientMockRecorder) ConnectWebsocket(ctx, domain, path any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ConnectWebsocket", reflect.TypeOf((*MockClient)(nil).ConnectWebsocket), ctx, domain, path)
}

// GetAck mocks base method.
func (m *MockClient) GetAck(ctx context.Context, from, to string, opts *client.Options) (core.Ack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAck", ctx, from, to, opts)
	ret0, _ := ret[0].(core.Ack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAck indicates an expected call of GetAck.
func (mr *MockClientMockRecorder) GetAck(ctx, from, to, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAck", reflect.TypeOf((*MockClient)(nil).GetAck), ctx, from, to, opts)
}

// GetAssociation mocks base method.
func (m *MockClient) GetAssociation(ctx context.Context, id string, opts *client.Options) (core.Association, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAssociation", ctx, id, opts)
	ret0, _ := ret[0].(core.Association)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAssociation indicates an expected call of GetAssociation.
func (mr *MockClientMockRecorder) GetAssociation(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAssociation", reflect.TypeOf((*MockClient)(nil).GetAssociation), ctx, id, opts)
}

// GetChunkBodies mocks base method.
func (m *MockClient) GetChunkBodies(ctx context.Context, query map[string]string, opts *client.Options) (map[string]core.Chunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChunkBodies", ctx, query, opts)
	ret0, _ := ret[0].(map[string]core.Chunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChunkBodies indicates an expected call of GetChunkBodies.
func (mr *MockClientMockRecorder) GetChunkBodies(ctx, query, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChunkBodies", reflect.TypeOf((*MockClient)(nil).GetChunkBodies), ctx, query, opts)
}

// GetChunkItrs mocks base method.
func (m *MockClient) GetChunkItrs(ctx context.Context, timelines []string, epoch string, opts *client.Options) (map[string]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChunkItrs", ctx, timelines, epoch, opts)
	ret0, _ := ret[0].(map[string]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChunkItrs indicates an expected call of GetChunkItrs.
func (mr *MockClientMockRecorder) GetChunkItrs(ctx, timelines, epoch, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChunkItrs", reflect.TypeOf((*MockClient)(nil).GetChunkItrs), ctx, timelines, epoch, opts)
}

// GetChunks mocks base method.
func (m *MockClient) GetChunks(ctx context.Context, timelines []string, queryTime time.Time, opts *client.Options) (map[string]core.Chunk, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChunks", ctx, timelines, queryTime, opts)
	ret0, _ := ret[0].(map[string]core.Chunk)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChunks indicates an expected call of GetChunks.
func (mr *MockClientMockRecorder) GetChunks(ctx, timelines, queryTime, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChunks", reflect.TypeOf((*MockClient)(nil).GetChunks), ctx, timelines, queryTime, opts)
}

// GetDomain mocks base method.
func (m *MockClient) GetDomain(ctx context.Context, domain string, opts *client.Options) (core.Domain, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDomain", ctx, domain, opts)
	ret0, _ := ret[0].(core.Domain)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetDomain indicates an expected call of GetDomain.
func (mr *MockClientMockRecorder) GetDomain(ctx, domain, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDomain", reflect.TypeOf((*MockClient)(nil).GetDomain), ctx, domain, opts)
}

// GetEntity mocks base method.
func (m *MockClient) GetEntity(ctx context.Context, address string, opts *client.Options) (core.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEntity", ctx, address, opts)
	ret0, _ := ret[0].(core.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEntity indicates an expected call of GetEntity.
func (mr *MockClientMockRecorder) GetEntity(ctx, address, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEntity", reflect.TypeOf((*MockClient)(nil).GetEntity), ctx, address, opts)
}

// GetKey mocks base method.
func (m *MockClient) GetKey(ctx context.Context, id string, opts *client.Options) ([]core.Key, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetKey", ctx, id, opts)
	ret0, _ := ret[0].([]core.Key)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetKey indicates an expected call of GetKey.
func (mr *MockClientMockRecorder) GetKey(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetKey", reflect.TypeOf((*MockClient)(nil).GetKey), ctx, id, opts)
}

// GetMessage mocks base method.
func (m *MockClient) GetMessage(ctx context.Context, id string, opts *client.Options) (core.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMessage", ctx, id, opts)
	ret0, _ := ret[0].(core.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMessage indicates an expected call of GetMessage.
func (mr *MockClientMockRecorder) GetMessage(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMessage", reflect.TypeOf((*MockClient)(nil).GetMessage), ctx, id, opts)
}

// GetProfile mocks base method.
func (m *MockClient) GetProfile(ctx context.Context, address string, opts *client.Options) (core.Profile, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetProfile", ctx, address, opts)
	ret0, _ := ret[0].(core.Profile)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetProfile indicates an expected call of GetProfile.
func (mr *MockClientMockRecorder) GetProfile(ctx, address, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetProfile", reflect.TypeOf((*MockClient)(nil).GetProfile), ctx, address, opts)
}

// GetRetracted mocks base method.
func (m *MockClient) GetRetracted(ctx context.Context, timelines []string, opts *client.Options) (map[string][]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRetracted", ctx, timelines, opts)
	ret0, _ := ret[0].(map[string][]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRetracted indicates an expected call of GetRetracted.
func (mr *MockClientMockRecorder) GetRetracted(ctx, timelines, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRetracted", reflect.TypeOf((*MockClient)(nil).GetRetracted), ctx, timelines, opts)
}

// GetTimeline mocks base method.
func (m *MockClient) GetTimeline(ctx context.Context, id string, opts *client.Options) (core.Timeline, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTimeline", ctx, id, opts)
	ret0, _ := ret[0].(core.Timeline)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTimeline indicates an expected call of GetTimeline.
func (mr *MockClientMockRecorder) GetTimeline(ctx, id, opts any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTimeline", reflect.TypeOf((*MockClient)(nil).GetTimeline), ctx, id, opts)
}

// RegisterHostRemap mocks base method.
func (m *MockClient) RegisterHostRemap(host, remap string, useHttps bool) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "RegisterHostRemap", host, remap, useHttps)
}

// RegisterHostRemap indicates an expected call of RegisterHostRemap.
func (mr *MockClientMockRecorder) RegisterHostRemap(host, remap, useHttps any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RegisterHostRemap", reflect.TypeOf((*MockClient)(nil).RegisterHostRemap), host, remap, useHttps)
}

// SetUserAgent mocks base method.
func (m *MockClient) SetUserAgent(software, version string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserAgent", software, version)
}

// SetUserAgent indicates an expected call of SetUserAgent.
func (mr *MockClientMockRecorder) SetUserAgent(software, version any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserAgent", reflect.TypeOf((*MockClient)(nil).SetUserAgent), software, version)
}
