// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/repository.go
//

// Package mock_ack is a generated GoMock package.
package mock_ack

import (
	context "context"
	reflect "reflect"

	core "github.com/concrnt/concrnt/core"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Ack mocks base method.
func (m *MockRepository) Ack(ctx context.Context, ack *core.Ack) (core.Ack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack", ctx, ack)
	ret0, _ := ret[0].(core.Ack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Ack indicates an expected call of Ack.
func (mr *MockRepositoryMockRecorder) Ack(ctx, ack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockRepository)(nil).Ack), ctx, ack)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, from, to string) (core.Ack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, from, to)
	ret0, _ := ret[0].(core.Ack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, from, to any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, from, to)
}

// GetAcker mocks base method.
func (m *MockRepository) GetAcker(ctx context.Context, key string) ([]core.Ack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAcker", ctx, key)
	ret0, _ := ret[0].([]core.Ack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAcker indicates an expected call of GetAcker.
func (mr *MockRepositoryMockRecorder) GetAcker(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAcker", reflect.TypeOf((*MockRepository)(nil).GetAcker), ctx, key)
}

// GetAcking mocks base method.
func (m *MockRepository) GetAcking(ctx context.Context, key string) ([]core.Ack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAcking", ctx, key)
	ret0, _ := ret[0].([]core.Ack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAcking indicates an expected call of GetAcking.
func (mr *MockRepositoryMockRecorder) GetAcking(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAcking", reflect.TypeOf((*MockRepository)(nil).GetAcking), ctx, key)
}

// Unack mocks base method.
func (m *MockRepository) Unack(ctx context.Context, ack *core.Ack) (core.Ack, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Unack", ctx, ack)
	ret0, _ := ret[0].(core.Ack)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Unack indicates an expected call of Unack.
func (mr *MockRepositoryMockRecorder) Unack(ctx, ack any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Unack", reflect.TypeOf((*MockRepository)(nil).Unack), ctx, ack)
}
