// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/repository.go
//

// Package mock_entity is a generated GoMock package.
package mock_entity

import (
	context "context"
	reflect "reflect"

	core "github.com/concrnt/concrnt/core"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Count mocks base method.
func (m *MockRepository) Count(ctx context.Context) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Count", ctx)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockRepositoryMockRecorder) Count(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockRepository)(nil).Count), ctx)
}

// Delete mocks base method.
func (m *MockRepository) Delete(ctx context.Context, key string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockRepositoryMockRecorder) Delete(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepository)(nil).Delete), ctx, key)
}

// DeleteMeta mocks base method.
func (m *MockRepository) DeleteMeta(ctx context.Context, ccid string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteMeta", ctx, ccid)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteMeta indicates an expected call of DeleteMeta.
func (mr *MockRepositoryMockRecorder) DeleteMeta(ctx, ccid any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteMeta", reflect.TypeOf((*MockRepository)(nil).DeleteMeta), ctx, ccid)
}

// Get mocks base method.
func (m *MockRepository) Get(ctx context.Context, key string) (core.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, key)
	ret0, _ := ret[0].(core.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockRepositoryMockRecorder) Get(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockRepository)(nil).Get), ctx, key)
}

// GetByAlias mocks base method.
func (m *MockRepository) GetByAlias(ctx context.Context, alias string) (core.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByAlias", ctx, alias)
	ret0, _ := ret[0].(core.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByAlias indicates an expected call of GetByAlias.
func (mr *MockRepositoryMockRecorder) GetByAlias(ctx, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByAlias", reflect.TypeOf((*MockRepository)(nil).GetByAlias), ctx, alias)
}

// GetList mocks base method.
func (m *MockRepository) GetList(ctx context.Context) ([]core.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", ctx)
	ret0, _ := ret[0].([]core.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList.
func (mr *MockRepositoryMockRecorder) GetList(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockRepository)(nil).GetList), ctx)
}

// GetMeta mocks base method.
func (m *MockRepository) GetMeta(ctx context.Context, key string) (core.EntityMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMeta", ctx, key)
	ret0, _ := ret[0].(core.EntityMeta)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMeta indicates an expected call of GetMeta.
func (mr *MockRepositoryMockRecorder) GetMeta(ctx, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMeta", reflect.TypeOf((*MockRepository)(nil).GetMeta), ctx, key)
}

// SetAlias mocks base method.
func (m *MockRepository) SetAlias(ctx context.Context, id, alias string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetAlias", ctx, id, alias)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetAlias indicates an expected call of SetAlias.
func (mr *MockRepositoryMockRecorder) SetAlias(ctx, id, alias any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetAlias", reflect.TypeOf((*MockRepository)(nil).SetAlias), ctx, id, alias)
}

// SetTombstone mocks base method.
func (m *MockRepository) SetTombstone(ctx context.Context, id, document, signature string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetTombstone", ctx, id, document, signature)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetTombstone indicates an expected call of SetTombstone.
func (mr *MockRepositoryMockRecorder) SetTombstone(ctx, id, document, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetTombstone", reflect.TypeOf((*MockRepository)(nil).SetTombstone), ctx, id, document, signature)
}

// UpdateMeta mocks base method.
func (m *MockRepository) UpdateMeta(ctx context.Context, key, info string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateMeta", ctx, key, info)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateMeta indicates an expected call of UpdateMeta.
func (mr *MockRepositoryMockRecorder) UpdateMeta(ctx, key, info any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateMeta", reflect.TypeOf((*MockRepository)(nil).UpdateMeta), ctx, key, info)
}

// UpdateScore mocks base method.
func (m *MockRepository) UpdateScore(ctx context.Context, id string, score int) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateScore", ctx, id, score)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateScore indicates an expected call of UpdateScore.
func (mr *MockRepositoryMockRecorder) UpdateScore(ctx, id, score any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateScore", reflect.TypeOf((*MockRepository)(nil).UpdateScore), ctx, id, score)
}

// UpdateTag mocks base method.
func (m *MockRepository) UpdateTag(ctx context.Context, id, tag string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateTag", ctx, id, tag)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateTag indicates an expected call of UpdateTag.
func (mr *MockRepositoryMockRecorder) UpdateTag(ctx, id, tag any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateTag", reflect.TypeOf((*MockRepository)(nil).UpdateTag), ctx, id, tag)
}

// Upsert mocks base method.
func (m *MockRepository) Upsert(ctx context.Context, entity core.Entity) (core.Entity, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Upsert", ctx, entity)
	ret0, _ := ret[0].(core.Entity)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Upsert indicates an expected call of Upsert.
func (mr *MockRepositoryMockRecorder) Upsert(ctx, entity any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Upsert", reflect.TypeOf((*MockRepository)(nil).Upsert), ctx, entity)
}

// UpsertWithMeta mocks base method.
func (m *MockRepository) UpsertWithMeta(ctx context.Context, entity core.Entity, meta core.EntityMeta) (core.Entity, core.EntityMeta, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpsertWithMeta", ctx, entity, meta)
	ret0, _ := ret[0].(core.Entity)
	ret1, _ := ret[1].(core.EntityMeta)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// UpsertWithMeta indicates an expected call of UpsertWithMeta.
func (mr *MockRepositoryMockRecorder) UpsertWithMeta(ctx, entity, meta any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpsertWithMeta", reflect.TypeOf((*MockRepository)(nil).UpsertWithMeta), ctx, entity, meta)
}
