// Code generated by MockGen. DO NOT EDIT.
// Source: repository.go
//
// Generated by this command:
//
//	mockgen -source=repository.go -destination=mock/repository.go
//

// Package mock_job is a generated GoMock package.
package mock_job

import (
	context "context"
	reflect "reflect"
	time "time"

	core "github.com/concrnt/concrnt/core"
	gomock "go.uber.org/mock/gomock"
)

// MockRepository is a mock of Repository interface.
type MockRepository struct {
	ctrl     *gomock.Controller
	recorder *MockRepositoryMockRecorder
}

// MockRepositoryMockRecorder is the mock recorder for MockRepository.
type MockRepositoryMockRecorder struct {
	mock *MockRepository
}

// NewMockRepository creates a new mock instance.
func NewMockRepository(ctrl *gomock.Controller) *MockRepository {
	mock := &MockRepository{ctrl: ctrl}
	mock.recorder = &MockRepositoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepository) EXPECT() *MockRepositoryMockRecorder {
	return m.recorder
}

// Cancel mocks base method.
func (m *MockRepository) Cancel(ctx context.Context, id string) (core.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Cancel", ctx, id)
	ret0, _ := ret[0].(core.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Cancel indicates an expected call of Cancel.
func (mr *MockRepositoryMockRecorder) Cancel(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Cancel", reflect.TypeOf((*MockRepository)(nil).Cancel), ctx, id)
}

// Clean mocks base method.
func (m *MockRepository) Clean(ctx context.Context, olderThan time.Time) ([]core.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Clean", ctx, olderThan)
	ret0, _ := ret[0].([]core.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Clean indicates an expected call of Clean.
func (mr *MockRepositoryMockRecorder) Clean(ctx, olderThan any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Clean", reflect.TypeOf((*MockRepository)(nil).Clean), ctx, olderThan)
}

// Complete mocks base method.
func (m *MockRepository) Complete(ctx context.Context, id, status, result string) (core.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Complete", ctx, id, status, result)
	ret0, _ := ret[0].(core.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Complete indicates an expected call of Complete.
func (mr *MockRepositoryMockRecorder) Complete(ctx, id, status, result any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Complete", reflect.TypeOf((*MockRepository)(nil).Complete), ctx, id, status, result)
}

// Dequeue mocks base method.
func (m *MockRepository) Dequeue(ctx context.Context) (*core.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dequeue", ctx)
	ret0, _ := ret[0].(*core.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dequeue indicates an expected call of Dequeue.
func (mr *MockRepositoryMockRecorder) Dequeue(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dequeue", reflect.TypeOf((*MockRepository)(nil).Dequeue), ctx)
}

// Enqueue mocks base method.
func (m *MockRepository) Enqueue(ctx context.Context, author, typ, payload string, scheduled time.Time) (core.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, author, typ, payload, scheduled)
	ret0, _ := ret[0].(core.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockRepositoryMockRecorder) Enqueue(ctx, author, typ, payload, scheduled any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockRepository)(nil).Enqueue), ctx, author, typ, payload, scheduled)
}

// List mocks base method.
func (m *MockRepository) List(ctx context.Context, authorID string) ([]core.Job, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List", ctx, authorID)
	ret0, _ := ret[0].([]core.Job)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockRepositoryMockRecorder) List(ctx, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockRepository)(nil).List), ctx, authorID)
}
